### ISSUE TITLE
ReferenceError: 'fileExists' is not defined in main.js

### ISSUE THREAD

**Issue by nmatt0** [bettercap/scripts#2]
I have cloned this project and have attempted to run the main.js script as a part of trying to understand how to write bettercap scripts. When I run the main.js script with bettercap I get the following error:

```
bettercap v2.32.0 (built for linux amd64 with go1.18.1) [type 'help' for a list of commands]

error loading main.js: ReferenceError: 'fileExists' is not defined
```

It seems like there are some common javascript functions that are not available in my environment. Any idea on what I'm doing wrong?

**Comment by evilsocket** [comment]
fileExists has been introduced after v2.32.0, you will need to clone this repo and use the master branch
